In [1]:
# load model
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

model_file_name='model.pickle'
with open(model_file_name, 'rb') as f:
    random_forest = pickle.load(f)

#fare_clf= StandardScaler()
fare_file_name='fare.pickle'
with open(fare_file_name, 'rb') as f:
    fare_clf = pickle.load(f)
    

In [2]:
def far_transform(fare1):
    return fare_clf.transform([[fare1]])[0]

def convert_age(age1):
    return age1 // 5 * 5

dict1 = { 'Cherbourg': 0, 'Queenstown': 1, 'Southampton': 2}
def convert_embark_town(embark1):
    return dict1[embark1]


In [3]:
X = []
# pclass	sex	age	sibsp	parch	fare	embark_town
X.append([3, 0, convert_age(22), 1, 0, far_transform(7.25), convert_embark_town('Southampton')])
X.append([1, 1, convert_age(35), 1, 0, far_transform(71.2833), convert_embark_town('Cherbourg')])
X=np.array(X)
X


array([[3, 0, 20, 1, 0, array([-0.50244517]), 2],
       [1, 1, 35, 1, 0, array([0.78684529]), 0]], dtype=object)

In [4]:
random_forest.predict_proba(X)

array([[0.94066667, 0.05933333],
       [0.02      , 0.98      ]])

In [5]:
random_forest.predict(X)

array([0, 1], dtype=int64)

In [3]:
from functools import reduce
reduce((0,1))

TypeError: reduce expected at least 2 arguments, got 1